Monthly_Reporting/Controllers/PenaltyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Monthly_Reporting.Models;
using Monthly_Reporting.Properties;

namespace Monthly_Reporting.Controllers
{
    public class PenaltyController : Controller
    {
        SqlConnection sqlcon = new SqlConnection();
        Utility mutility = new Utility();
        // GET: Penalty
        public ActionResult Index()
        {
            DataTable dt = new DataTable();
            DataTable dt_main_menu = new DataTable();
            mutility.DbName = Settings.Default["DbName"].ToString();
            mutility.UserName = Settings.Default["UserName"].ToString();
            mutility.Password = Settings.Default["Password"].ToString();
            mutility.ServerName = Settings.Default["ServerName"].ToString();

            if (mutility.ServerName == "" || mutility.DbName == "" || mutility.UserName == "")
            {
                return RedirectToAction("Index", "Setting_Connection/Index");
            }
            else
            {
                if (Session["ID"] != null)
                {
                    UserAccessRightController UsAccRight = new UserAccessRightController();
                    string userkey = Session["user_key"].ToString();
                    dt = UsAccRight.UserAccessRight(userkey);
                    dt_main_menu = UsAccRight.Main_Menu(userkey);
                    ViewBag.manin_menu = dt_main_menu;
                    ViewBag.sub_manin = dt;
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Login/Index");
                }
            }
        }
        public ActionResult Summary_mfi()
        {
            DataTable dt = new DataTable();
            DataTable dt_main_menu = new DataTable();


            mutility.DbName = Settings.Default["DbName"].ToString();
            mutility.UserName = Settings.Default["UserName"].ToString();
            mutility.Password = Settings.Default["Password"].ToString();
            mutility.ServerName = Settings.Default["ServerName"].ToString();

            if (mutility.ServerName == "" || mutility.DbName == "" || mutility.UserName == "")
            {
                return RedirectToAction("Index", "Setting_Connection/Index");
            }
            else
            {
                if (Session["ID"] != null)
                {
                    UserAccessRightController UsAccRight = new UserAccessRightController();

                    string userkey = Session["user_key"].ToString();
                    dt = UsAccRight.UserAccessRight(userkey);
                    dt_main_menu = UsAccRight.Main_Menu(userkey);
                    ViewBag.manin_menu = dt_main_menu;
                    ViewBag.sub_manin = dt;
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Login/Index");
                }


            }
        }
        public ActionResult Full_Year_Monthly()
        {
            DataTable dt = new DataTable();
            DataTable dt_main_menu = new DataTable();


            mutility.DbName = Settings.Default["DbName"].ToString();
            mutility.UserName = Settings.Default["UserName"].ToString();
            mutility.Password = Settings.Default["Password"].ToString();
            mutility.ServerName = Settings.Default["ServerName"].ToString();

            if (mutility.ServerName == "" || mutility.DbName == "" || mutility.UserName == "")
            {
                return RedirectToAction("Index", "Setting_Connection/Index");
            }
            else
            {
                if (Session["ID"] != null)
                {
                    UserAccessRightController UsAccRight = new UserAccessRightController();

                    string userkey = Session["user_key"].ToString();
                    dt = UsAccRight.UserAccessRight(userkey);
                    dt_main_menu = UsAccRight.Main_Menu(userkey);
                    ViewBag.manin_menu = dt_main_menu;
                    ViewBag.sub_manin = dt;
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Login/Index");
                }


            }
        }
        public ActionResult Exception_All()
        {
            DataTable dt = new DataTable();
            DataTable dt_main_menu = new DataTable();


            mutility.DbName = Settings.Default["DbName"].ToString();
            mutility.UserName = Settings.Default["UserName"].ToString();
            mutility.Password = Settings.Default["Password"].ToString();
            mutility.ServerName = Settings.Default["ServerName"].ToString();

            if (mutility.ServerName == "" || mutility.DbName == "" || mutility.UserName == "")
            {
                return RedirectToAction("Index", "Setting_Connection/Index");
            }
            else
            {
                if (Session["ID"] != null)
                {
                    UserAccessRightController UsAccRight = new UserAccessRightController();

                    string userkey = Session["user_key"].ToString();
                    dt = UsAccRight.UserAccessRight(userkey);
                    dt_main_menu = UsAccRight.Main_Menu(userkey);
                    ViewBag.manin_menu = dt_main_menu;
                    ViewBag.sub_manin = dt;
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Login/Index");
                }


            }
        }
        public ActionResult Summary_All()
        {
            DataTable dt = new DataTable();
            DataTable dt_main_menu = new DataTable();


            mutility.DbName = Settings.Default["DbName"].ToString();
            mutility.UserName = Settings.Default["UserName"].ToString();
            mutility.Password = Settings.Default["Password"].ToString();
            mutility.ServerName = Settings.Default["ServerName"].ToString();

            if (mutility.ServerName == "" || mutility.DbName == "" || mutility.UserName == "")
            {
                return RedirectToAction("Index", "Setting_Connection/Index");
            }
            else
            {
                if (Session["ID"] != null)
                {
                    UserAccessRightController UsAccRight = new UserAccessRightController();

                    string userkey = Session["user_key"].ToString();
                    dt = UsAccRight.UserAccessRight(userkey);
                    dt_main_menu = UsAccRight.Main_Menu(userkey);
                    ViewBag.manin_menu = dt_main_menu;
                    ViewBag.sub_manin = dt;
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Login/Index");
                }


            }
        }
        public ActionResult Full_Year_Weekly()
        {
            DataTable dt = new DataTable();
            DataTable dt_main_menu = new DataTable();


            mutility.DbName = Settings.Default["DbName"].ToString();
            mutility.UserName = Settings.Default["UserName"].ToString();
            mutility.Password = Settings.Default["Password"].ToString();
            mutility.ServerName = Settings.Default["ServerName"].ToString();

            if (mutility.ServerName == "" || mutility.DbName == "" || mutility.UserName == "")
            {
                return RedirectToAction("Index", "Setting_Connection/Index");
            }
            else
            {
                if (Session["ID"] != null)
                {
                    UserAccessRightController UsAccRight = new UserAccessRightController();

                    string userkey = Session["user_key"].ToString();
                    dt = UsAccRight.UserAccessRight(userkey);
                    dt_main_menu = UsAccRight.Main_Menu(userkey);
                    ViewBag.manin_menu = dt_main_menu;
                    ViewBag.sub_manin = dt;
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Login/Index");
                }


            }
        }
        }    
    }

Monthly_Reporting/Views/Penalty/Exception_All.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <span style="font-size:16px;color:black">
                        <i class="fa fa-edit"></i> របាយការណ៍សង្ខេបប្រមូលប្រាក់ពិន័យប្រចាំខែសម្រាប់អតិថិជនយឺតយ៉ា​វ
                    </span>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="#">Settings 1</a>
                                </li>
                                <li>
                                    <a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="breadcrumb flat row nopadding" style="margin-top:-10px;">
                        <a href="@Url.Action("Index","Penalty")">Exception (MFI)</a>
                        <a href="@Url.Action("Summary_mfi","Penalty")">Summary MFI</a>
                        <a href="@Url.Action("Full_Year_Monthly","Penalty")">Full Year Monthly</a>
                        <a href="@Url.Action("Exception_All","Penalty")" class="active">Exception All</a>
                        <a href="@Url.Action("Summary_All","Penalty")">Summary NGO & MFI</a>
                        <a href="@Url.Action("Full_Year_Weekly","Penalty")">Full Year Weekly</a>
                    </div>
                    <p></p>
                    <div class="table-responsive">
                        <div class="row nopadding">
                            <div class="col-md-6"></div>
                            <div class="col-md-6 nopadding">
                                <span class="pull-right">
                                    <button type="button" class="btn btn-primary" onclick="javascript:printDiv('print_report')"><i class="fa fa-save"></i> Print</button>
                                </span>
                                <span class="pull-right">
                                    <button type="button" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Excel</button>
                                </span>
                            </div>
                        </div>
                        <div id="print_report">
                            <div class="col-md-12" style="display:none;" id="header_print">
                                <div style="text-align:center;margin-left:250px;">
                                    <img src="~/assets/images/report_logo.png" alt="user" style="width:90px;margin-top:20px;">
                                    <img src="~/assets/images/logo_main.PNG" style="width:380px;" alt="user">
                                </div>

                                <h5 style="color:rgba(0,0,0,0.87);text-align:center;margin-left:320px;font-weight:bold;text-decoration: underline">របាយការណ៍សង្ខេបប្រមូលប្រាក់ពិន័យប្រចាំខែសម្រាប់អតិថិជនយឺតយ៉ា​វ</h5>
                                <div class="row"> <span style="font-weight:bold;">នាយកដ្ឋានព័ត៌មានវិទ្យា</span></div>
                                <div class="row"> <span style="font-weight:bold;">ផ្នែកគ្រប់គ្រង និងគាំទ្រប្រព័ន្ធ</span></div>

                                <br />
                            </div>
                            <table class="table table-bordered">
                                <thead>
                                    <tr class="active">
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">ល.រ</td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">កូដសាខា</td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">ឈ្មោះសាខា</td>
                                        <td style="text-align:center" colspan="3">
                                            ការប្រមូលប្រាក់ពិន័យ៥០០ ៛
                                        </td>
                                        <td style="text-align:center" colspan="3">
                                            ការប្រមូលប្រាក់ពិន័យស្វ័យប្រវត្តិ
                                        </td>
                                        <td style="text-align:center" colspan="3">
                                            សរុបការប្រមូលប្រាក់ពិន័យ

                                        </td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            ផែនការប្រមូល
                                            <p>ប្រាក់ពិន័យ</p>
                                        </td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            %នៃការប្រមូល
                                            <p>ប្រាក់ពិន័យបានបង់</p>
                                        </td>
                                    </tr>
                                    <tr class="active" style="boder;border-bottom:3pt solid #22d4ae;white-space: nowrap;overflow: hidden;">
                                        <td style="text-align:center">
                                            ចំនួនអតិថិជន
                                        </td>
                                        <td style="text-align:center">
                                            ទឹកប្រាក់
                                        </td>
                                        <td style="text-align:center">
                                            ទឹកប្រាក់បាន
                                            <p>លើកលែងពិន័យ</p>
                                        </td>
                                        <td style="text-align:center">
                                            ចំនួន
                                            អតិថិជន
                                        </td>
                                        <td style="text-align:center">
                                            ទឹកប្រាក់
                                        </td>
                                        <td style="text-align:center">
                                            ទឹកប្រាក់បាន
                                            <p>លើកលែងពិន័យ</p>
                                        </td>
                                        <td style="text-align:center">
                                            ចំនួនអតិថិជន
                                        </td>
                                        <td style="text-align:center">
                                            ទឹកប្រាក់
                                        </td>
                                        <td style="text-align:center">
                                            ទឹកប្រាក់បាន
                                            <p>លើកលែងពិន័យ</p>
                                        </td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>

                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </tbody>
                                <tfoot>
                                    <tr style="font-weight:bold;">
                                        <td style="text-align:right" colspan="3">សរុប </td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>

                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
    <!-- /page content -->
    <script>


    function printDiv(divID) {
    //Get the HTML of div
    var divElements = document.getElementById(divID).innerHTML;
    //Get the HTML of whole page
    var oldPage = document.body.innerHTML;
    //Reset the page's HTML with div's HTML onl
    document.body.innerHTML =
        "<html><head><title></title></head><body>" +
        divElements + "</body>";
        var table=document.getElementById("print_report");
        var r=0;
        //document.getElementById("header_print").style.display="inline-block";
        //document.getElementById("footer_print").style.display="inline-block";

    //Print Page
    window.print();
    //Restore orignal HTML
    document.body.innerHTML = oldPage;
    window.location.href="";
    //window.location.href="{{route('settlement.dashboard')}}";
    document.getElementById("checkbox").checked = false;
    }
    </script>

Monthly_Reporting/Views/Penalty/Full_Year_Monthly.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <span style="font-size:16px;color:black">
                        <i class="fa fa-edit"></i> របាយការណ៍សង្ខេបប្រមូលប្រាក់ពិន័យប្រចាំខែសម្រាប់អតិថិជនយឺតយ៉ា​វ
                    </span>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="#">Settings 1</a>
                                </li>
                                <li>
                                    <a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="breadcrumb flat row nopadding" style="margin-top:-10px;">
                        <a href="@Url.Action("Index","Penalty")">Exception (MFI)</a>
                        <a href="@Url.Action("Summary_mfi","Penalty")">Summary MFI</a>
                        <a href="@Url.Action("Full_Year_Monthly","Penalty")" class="active">Full Year Monthly</a>
                        <a href="@Url.Action("Exception_All","Penalty")">Exception All</a>
                        <a href="@Url.Action("Summary_All","Penalty")">Summary NGO & MFI</a>
                        <a href="@Url.Action("Full_Year_Weekly","Penalty")">Full Year Weekly</a>
                    </div>
                    <p></p>
                    <div class="table-responsive">
                        <div class="row nopadding">
                            <div class="col-md-6"></div>
                            <div class="col-md-6 nopadding">
                                <span class="pull-right">
                                    <button type="button" class="btn btn-primary" onclick="javascript:printDiv('print_report')"><i class="fa fa-save"></i> Print</button>
                                </span>
                                <span class="pull-right">
                                    <button type="button" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Excel</button>
                                </span>
                            </div>
                        </div>
                        <div id="print_report">
                            <div class="col-md-12" style="display:none;" id="header_print">
                                <div style="text-align:center;margin-left:250px;">
                                    <img src="~/assets/images/report_logo.png" alt="user" style="width:90px;margin-top:20px;">
                                    <img src="~/assets/images/logo_main.PNG" style="width:380px;" alt="user">
                                </div>

                                <h5 style="color:rgba(0,0,0,0.87);text-align:center;margin-left:320px;font-weight:bold;text-decoration: underline">របាយការណ៍សង្ខេបប្រមូលប្រាក់ពិន័យប្រចាំខែសម្រាប់អតិថិជនយឺតយ៉ា​វ</h5>
                                <div class="row"> <span style="font-weight:bold;">នាយកដ្ឋានព័ត៌មានវិទ្យា</span></div>
                                <div class="row"> <span style="font-weight:bold;">ផ្នែកគ្រប់គ្រង និងគាំទ្រប្រព័ន្ធ</span></div>

                                <br />
                            </div>
                            <table class="table table-bordered">
                                <thead>
                                    <tr class="active">
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">ល.រ</td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">សាខា</td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">កូដសាខា</td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            សរុប ២០១៨
                                        </td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            មករា/២០១៩
                                        </td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            កុម្ភៈ/២០១៩
                                        </td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            មិនា/២០១៩
                                        </td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            មេសា/២០១៩

                                        </td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            ឧសភា/២០១៩

                                        </td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            មិថុនា/២០១៩

                                        </td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            កក្កដា/២០១៩

                                        </td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            សីហា/២០១៩


                                        </td>

                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            កញ្ញា/២០១៩


                                        </td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            តុលា/២០១៩


                                        </td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            វិច្ឆិកា/២០១៩


                                        </td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            ធ្នូ/២០១៩


                                        </td>
                                        <td style="vertical-align:middle;boder;border-bottom:3pt solid #22d4ae;" rowspan="3">
                                            សរុប ២០១៩



                                        </td>

                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>

                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </tbody>
                                <tfoot>
                                    <tr style="font-weight:bold;">
                                        <td style="text-align:right" colspan="3">សរុប </td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>

                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
    <!-- /page content -->
    <script>


    function printDiv(divID) {
    //Get the HTML of div
    var divElements = document.getElementById(divID).innerHTML;
    //Get the HTML of whole page
    var oldPage = document.body.innerHTML;
    //Reset the page's HTML with div's HTML onl
    document.body.innerHTML =
        "<html><head><title></title></head><body>" +
        divElements + "</body>";
        var table=document.getElementById("print_report");
        var r=0;
        //document.getElementById("header_print").style.display="inline-block";
        //document.getElementById("footer_print").style.display="inline-block";

    //Print Page
    window.print();
    //Restore orignal HTML
    document.body.innerHTML = oldPage;
    window.location.href="";
    //window.location.href="{{route('settlement.dashboard')}}";
    document.getElementById("checkbox").checked = false;
    }
    </script>