Monthly_Reporting/Controllers/ConsumerEnquiryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using Monthly_Reporting.Models;
namespace Monthly_Reporting.Controllers
{
    public class ConsumerEnquiryController : Controller
    {
        Utility Ut = new Utility();
        Core.WHelper helper = new Core.WHelper();
        DataTable dtSubMenu = new DataTable();
        DataTable dtMenu = new DataTable();
        DataTable dtReport = new DataTable();
        DataTable dtRun = new DataTable();
        readonly Reports rs = new Reports();

        Controllers.UserAccessRightController UsAccRight = new Controllers.UserAccessRightController();
        public ActionResult Is_Checking()
        {

            Controllers.UserAccessRightController UsAccRight = new Controllers.UserAccessRightController();

            string userkey = Convert.ToString(Session["user_key"]);
            dtSubMenu = UsAccRight.UserAccessRight(userkey);
            dtMenu = UsAccRight.Main_Menu(userkey);

            if (helper.CheckExitConnection(Convert.ToString(Session["ServerName"]), Convert.ToString(Session["DbName"]), Convert.ToString(Session["UserName"])) == true)
            {
                return RedirectToAction("Index", "Setting_Connection/Index");
            }

            //Check Session

            if (Session["ID"] == null) { return RedirectToAction("Index", "Login/Index"); }
            return View();
        }
        // GET: ConsumerEnquiry
        public ActionResult Index()
        {
            //Check Config
            this.Is_Checking();
            string userkey = Convert.ToString(Session["user_key"]);

            //Check Config

            ViewBag.message = "No";
            ViewBag.manin_menu = UsAccRight.Main_Menu(userkey);
            ViewBag.sub_manin = UsAccRight.UserAccessRight(userkey);

            ViewBag.dtLocationCode = Ut.LocationCode(1,1,"0");
            ViewBag.dtReport = Ut.ListReport(Ut.ArrayOfReportList(Convert.ToString(Session["report_code"])));
            ViewBag.dt_ManageZone = Ut.ZoneControl(Ut.ArrayOfZoneList(userkey));
            return View();
        }
        public ActionResult Enquiry(Reports rs)
        {
            //Check Config
            this.Is_Checking();
            string userkey = Convert.ToString(Session["user_key"]);

            //Check Config


            ViewBag.manin_menu = UsAccRight.Main_Menu(userkey);
            ViewBag.sub_manin = UsAccRight.UserAccessRight(userkey);
            ViewBag.message = "No";
            ViewBag.dtLocationCode = Ut.LocationCode(1, 1, "0");
            ViewBag.dt_ManageZone = Ut.ZoneControl(Ut.ArrayOfZoneList(userkey));
            if (rs.submit == "submit")
            {
                //ViewBag.message = "ព័ត៌មានដែលអ្នកស្វែងរកមិនមានទេ";
                return RedirectToAction("ViewEnquiry");
            }
            return View("Index");
        }
        
        public string DisplayDistrict(string ProvinceCode)
        {
            DataTable dtDistrict = new DataTable();
            dtDistrict = Ut.LocationCode(2, 1, ProvinceCode);
            string District_display = "";
            District_display = "<option value = '0' selected='selected'> ជ្រើសរើសស្រុក </ option >";
            foreach (DataRow dr in dtDistrict.Rows)
            {
                
                District_display += "<option value=" + dr["DCode"].ToString() + ">" + dr["District"].ToString() + "</option>";
            }
            return District_display;
        }
        public string DisplayCommune(string DistrictCode)
        {
            DataTable dtCommune = new DataTable();
            dtCommune = Ut.LocationCode(3, 1, DistrictCode);
            string Commune_display = "";
            Commune_display = "<option value = '0' selected='selected'> ជ្រើសរើសឃុំសង្កាត់ </ option >";
            foreach (DataRow dr in dtCommune.Rows)
            {
                
                Commune_display += "<option value=" + dr["CCode"].ToString() + ">" + dr["Commune"].ToString() + "</option>";
            }
            return Commune_display;
        }
        
        public ActionResult ViewEnquiry(Reports rs)
        {
            //Check Config
            this.Is_Checking();
            string userkey = Convert.ToString(Session["user_key"]);

            //Check Config

            ViewBag.message = "No";
            ViewBag.manin_menu = UsAccRight.Main_Menu(userkey);
            ViewBag.sub_manin = UsAccRight.UserAccessRight(userkey);

            ViewBag.dtLocationCode = Ut.LocationCode(1, 1, "0");
            ViewBag.dtReport = Ut.ListReport(Ut.ArrayOfReportList(Convert.ToString(Session["report_code"])));
            ViewBag.dt_ManageZone = Ut.ZoneControl(Ut.ArrayOfZoneList(userkey));
            return View();
        }
    }
}

Monthly_Reporting/Views/ConsumerEnquiry/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Data;
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <span style="font-size:16px;color:black"><i class="fa fa-edit"></i> ព័ត៌មានលម្អិតផ្ទាល់ខ្លួនរបស់អតិថិជន</span>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="#">Settings 1</a>
                                </li>
                                <li>
                                    <a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form action="@Url.Action("Enquiry", "ConsumerEnquiry")" method="post">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group col-sm-4 nopadding">
                                    <label for="exampleInputEmail1">ប្រភេទអត្តសញ្ញាណប័ណ្ណ</label>
                                    <select class="form-control" id="IdType">
                                        <option value="1">អត្តសញ្ញាណប័ណ្ណ</option>
                                        <option value="2">សៀវភៅគ្រួសារ</option>
                                        <option value="3">សៀវភៅស្នាក់នៅ</option>
                                        <option value="4">សំបុត្រកំណើត</option>
                                        <option value="1"></option>
                                    </select>
                                </div>
                                <div class="form-group col-sm-4">
                                    <label for="exampleInputEmail1">លេខអត្តសញ្ញាណប័ណ្ណ</label>
                                    <input type="text" class="col-sm-2 form-control" placeholder="លេខអត្តសញ្ញាណប័ណ្ណ">
                                </div>
                                <div class="form-group col-sm-4 nopadding">
                                    <div class="col-sm-6 ">
                                        <label for="exampleInputEmail1">ភេទ</label>
                                        <select class="form-control" id="Gender">
                                            <option value="M">ប្រុស</option>
                                            <option value="F">ស្រី</option>
                                        </select>
                                    </div>
                                    <div class="col-sm-6 nopadding">
                                        <label for="exampleInputEmail1">ថ្ងៃខែ​ឆ្នាំ​កំណើត</label>
                                        <input type="text" class="col-sm-2 form-control" id="dob" placeholder="ថ្ងៃខែ​ឆ្នាំ​កំណើត">
                                    </div>


                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group col-sm-4 nopadding">
                                    <label for="exampleInputEmail1">នាមត្រកូល (ខ្មែរ) </label>
                                    <input type="text" class="col-sm-2 form-control" id="dob" placeholder="នាមត្រកូល">
                                </div>

                                <div class="form-group col-sm-4">
                                    <label for="exampleInputEmail1">នាមខ្លួន (ខែ្មរ)</label>
                                    <input type="text" class="col-sm-2 form-control" id="dob" placeholder="នាមខ្លួន">
                                </div>

                                <div class="form-group col-sm-4 nopadding">
                                    <div class="col-sm-6">
                                        <label for="exampleInputEmail1">នាមត្រកូល (អង់គ្លេស)</label>
                                        <input type="text" class="col-sm-2 form-control" id="dob" placeholder="Family Name">
                                    </div>
                                    <div class="col-sm-6 nopadding">
                                        <label for="exampleInputEmail1">នាមខ្លួន (អង់គ្លេស)</label>
                                        <input type="text" class="col-sm-2 form-control" id="dob" placeholder="First Name">
                                    </div>

                                </div>

                            </div>
                            <div class="col-lg-12">

                                <div class="form-group col-sm-4 nopadding">
                                    <label for="exampleInputEmail1">ទីកន្លែងកំណើតខេត្ត</label>
                                    <select class="form-control" id="dobprovince">
                                        <option value="0">ជ្រើសរើសខេត្ត</option>
                                        @{
                                            foreach (DataRow dr in ViewBag.dtLocationCode.Rows)
                                            {
                                                <option value="@dr["PCode"].ToString()">@dr["Province"].ToString() </option>
                                            }
                                        }

                                    </select>
                                </div>

                                <div class="form-group col-sm-4">
                                    <label for="exampleInputEmail1">ទីកន្លែងកំណើតស្រុក</label>
                                    <select class="form-control" id="dobDistrict">
                                        <option value="0">ជ្រើសរើសស្រុក</option>
                                    </select>
                                </div>
                                <div class="form-group col-sm-4">
                                    <label for="exampleInputEmail1">ទីកន្លែងកំណើតឃុំសង្កាត់</label>
                                    <select class="form-control" id="dobCommune">
                                        <option value="0">ជ្រើសរើសឃុំសង្កាត់</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-sm-6"><button type="submit" value="submit" name="submit" class="btn btn-primary"><i class="fa fa-search"></i> ស្វែងរក</button></div>
                        </div>
                    </form>
                    @{
                        if (ViewBag.message == "No")
                        { 
                        }
                        else
                        {
                            <div class="col-lg-12">
                                <div class="alert alert-info" role="alert">@ViewBag.message</div>
                            </div>
                        }
                    }                    
                </div>                
            </div>  
        </div>
    </div>
</div>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
@Scripts.Render("~/Scripts/jquery.min.js")
<script>
            $(document).ready(function () {
                $('#IdType').select2();
                $('#Gender').select2();
                $('#dobprovince').select2();
                $('#dobDistrict').select2();
                $('#dobCommune').select2();
            });
            jQuery(document).ready(function () {

                $("#datestart").datepicker({
                    format: 'yyyy-mm-dd',
                    changeMonth: true,
                    changeYear: true,
                    yearRange: '+50y:c+nn',
                    maxDate: '-1d'
                });
                $("#dob").datepicker({
                    format: 'yyyy-mm-dd',
                    changeMonth: true,
                    changeYear: true,
                    yearRange: '+50y:c+nn',
                    maxDate: '-1d'
                });
            });
    $(document).ready(function () {
        var _token = $('meta[name="csrf-token"]').attr('content');
        //check branch name
        /*This mothed we create for get Commune code*/
        $("#dobDistrict").on("change", function ()
        {
            //console.log(dbcount);
            var DistrictCode = $(this).val().trim();
            $.ajax(
            {
                method: 'POST',
                url: "@Url.Action("DisplayCommune", "ConsumerEnquiry")",
                //dataType: "JSON",
                data: {
                    _token: _token,
                    DistrictCode: DistrictCode
                },
                success: function (data) {
                    $("#dobCommune").html("");
                    $("#dobCommune").html(data);
                },
                error: function (data) {
                $("#dobDistrict").html("");
                $("#dobCommune").html("");
                }
            });
        });

        /*This mothed create for get district code with ajax*/
        $("#dobprovince").on("change", function ()
        {
            $("#dobDistrict").html("");
            $("#dobCommune").html("");
            //console.log(dbcount);
            var ProvinceCode = $(this).val().trim();
            $.ajax(
            {
                method: 'POST',
                url: "@Url.Action("DisplayDistrict", "ConsumerEnquiry")",
                //dataType: "JSON",
                data: {
                    _token: _token,
                    ProvinceCode: ProvinceCode
                },
                    success: function (data) {  
                    $("#dobDistrict").html();                  
                    $("#dobDistrict").html(data);
                },
                error: function (data) {
                    $("#dobDistrict").html();                  
                }
            });
        });
        
    });

</script>
<style>
    legend {
        font-size: 12px;
    }

    .nopadding {
        padding: 0 !important;
        margin: 0 !important;
    }
</style>

Monthly_Reporting/Views/ConsumerEnquiry/ViewEnquiry.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Data;
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <img src="~/assets/images/report_logo.png" />
                    <span style="font-size:16px;color:black">គ្រឹះស្ថាន​មីក្រូ​ហិរញ្ញវត្ថុ ​សហគ្រិន​ភាព​ ភី​អិល​ស៊ី</span>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="#">Settings 1</a>
                                </li>
                                <li>
                                    <a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="col-md-6 col-sm-4 col-xs-12 nopadding">
                        <div class="x_panel tile">
                            <table class="table table-bordered">
                                <tr>
                                    <td><span style="font-weight:bold;">Applicant Type</span></td>
                                    <td colspan="2"><span style="font-weight:bold;">Primary</span></td>
                                </tr>
                                <tr>
                                    <td>ID Type and Number</td>
                                    <td>National ID 170911310</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>
                                <tr>
                                    <td colspan="3"><span style="font-weight:bold;">Khmer Name</span></td>
                                </tr>

                                <tr>
                                    <td>Family Name</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>First Name</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td colspan="3"><span style="font-weight:bold;">English Name</span></td>
                                </tr>

                                <tr>
                                    <td>Family Name</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>First Name</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Date of Birth</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Place of Birth Country</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>
                                <tr>
                                    <td>Place of Birth Province</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Place of Birth District</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Place of Birth Commune</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Gender</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>
                            </table>
                        </div>
                    </div>

                    <div class="col-md-12 col-sm-12 col-xs-12 nopadding">
                        <div class="x_panel tile">
                            <table class="table table-bordered">
                                <tr>
                                    <td><span style="font-weight:bold;">Total Accounts</span></td>
                                    <td colspan="2"><span style="font-weight:bold;">Primary</span></td>
                                </tr>
                                <tr>
                                    <td>Normal Accounts</td>
                                    <td>National ID 170911310</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Delinquent Accounts</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Closed Accounts</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Write Off Accounts</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Total Limits</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Total Liabilities</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Total Write Off Amounts</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>
                                <tr>
                                    <td>Outstanding Write Off Balance</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Place of Birth District</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Place of Birth Commune</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Gender</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>
                            </table>
                        </div>
                    </div>

                    <div class="col-md-12 col-sm-12 col-xs-12 nopadding">
                        <div class="x_panel tile">
                            <table class="table table-bordered">
                                <tr>
                                    <td><span style="font-weight:bold;">Total Accounts</span></td>
                                    <td colspan="2"><span style="font-weight:bold;">Primary</span></td>
                                </tr>
                                <tr>
                                    <td>Normal Accounts</td>
                                    <td>National ID 170911310</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Delinquent Accounts</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Closed Accounts</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Write Off Accounts</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Total Limits</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Total Liabilities</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Total Write Off Amounts</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>
                                <tr>
                                    <td>Outstanding Write Off Balance</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Place of Birth District</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Place of Birth Commune</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>

                                <tr>
                                    <td>Gender</td>
                                    <td>e</td>
                                    <td>(Family Book 272217នបខបប)</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@Scripts.Render("~/Scripts/jquery.min.js")

<style>
    legend {
        font-size: 12px;
    }

    .nopadding {
        padding: 0 !important;
        margin: 0 !important;
    }
</style>